
package myservices;

import java.util.ArrayList;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

import db.FlightBooking;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightBookingService", targetNamespace = "http://myservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FlightBookingService {


    /**
     * 
     * @param personName
     * @param flightDestination
     * @return
     *     returns myservices.FlightBooking
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://myservices/FlightBookingService/bookFlightRequest", output = "http://myservices/FlightBookingService/bookFlightResponse")
    public FlightBooking bookFlight(
        @WebParam(name = "personName", partName = "personName")
        String personName,
        @WebParam(name = "flightDestination", partName = "flightDestination")
        String flightDestination);

    /**
     * 
     * @return
     *     returns myservices.ArrayListOfFlightBooking
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://myservices/FlightBookingService/getAllBookingsRequest", output = "http://myservices/FlightBookingService/getAllBookingsResponse")
    public ArrayList<FlightBooking> getAllBookings();

    /**
     * 
     * @param flightId
     */
    @WebMethod
    @Action(input = "http://myservices/FlightBookingService/removeFlightRequest", output = "http://myservices/FlightBookingService/removeFlightResponse")
    public void removeFlight(
        @WebParam(name = "flightId", partName = "flightId")
        int flightId);

}
