
package myservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TripBookingServiceImplService", targetNamespace = "http://myservices/", wsdlLocation = "http://127.0.1.1:7001/hw8/TripBookingServiceImplService?WSDL")
public class TripBookingServiceImplService
    extends Service
{

    private final static URL TRIPBOOKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRIPBOOKINGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TRIPBOOKINGSERVICEIMPLSERVICE_QNAME = new QName("http://myservices/", "TripBookingServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.1.1:7001/hw8/TripBookingServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRIPBOOKINGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TRIPBOOKINGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TripBookingServiceImplService() {
        super(__getWsdlLocation(), TRIPBOOKINGSERVICEIMPLSERVICE_QNAME);
    }

    public TripBookingServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRIPBOOKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public TripBookingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TRIPBOOKINGSERVICEIMPLSERVICE_QNAME);
    }

    public TripBookingServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRIPBOOKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public TripBookingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TripBookingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TripBookingService
     */
    @WebEndpoint(name = "TripBookingServiceImplPort")
    public TripBookingService getTripBookingServiceImplPort() {
        return super.getPort(new QName("http://myservices/", "TripBookingServiceImplPort"), TripBookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TripBookingService
     */
    @WebEndpoint(name = "TripBookingServiceImplPort")
    public TripBookingService getTripBookingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://myservices/", "TripBookingServiceImplPort"), TripBookingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRIPBOOKINGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TRIPBOOKINGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TRIPBOOKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
