
package myservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import db.TripBooking;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(endpointInterface = "myservices.TripBookingService")
public interface TripBookingService {


    /**
     * 
     * @return 
     *     returns java.util.List<myservices.TripBooking>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBookings", targetNamespace = "http://myservices/", className = "myservices.GetAllBookings")
    @ResponseWrapper(localName = "getAllBookingsResponse", targetNamespace = "http://myservices/", className = "myservices.GetAllBookingsResponse")
    @Action(input = "http://myservices/TripBookingServiceImpl/getAllBookingsRequest", output = "http://myservices/TripBookingServiceImpl/getAllBookingsResponse")
    public List<TripBooking> getAllBookings();

    /**
     * 
     * @param personName
     * @param tripDestination
     * @return
     *     returns myservices.TripBooking
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookTrip", targetNamespace = "http://myservices/", className = "myservices.BookTrip")
    @ResponseWrapper(localName = "bookTripResponse", targetNamespace = "http://myservices/", className = "myservices.BookTripResponse")
    @Action(input = "http://myservices/TripBookingServiceImpl/bookTripRequest", output = "http://myservices/TripBookingServiceImpl/bookTripResponse")
    public TripBooking bookTrip(
        @WebParam(name = "personName", targetNamespace = "")
        String personName,
        @WebParam(name = "tripDestination", targetNamespace = "")
        String tripDestination);

    /**
     * 
     * @param tripId
     */
    @WebMethod
    @RequestWrapper(localName = "removeTrip", targetNamespace = "http://myservices/", className = "myservices.RemoveTrip")
    @ResponseWrapper(localName = "removeTripResponse", targetNamespace = "http://myservices/", className = "myservices.RemoveTripResponse")
    @Action(input = "http://myservices/TripBookingServiceImpl/removeTripRequest", output = "http://myservices/TripBookingServiceImpl/removeTripResponse")
    public void removeTrip(
        @WebParam(name = "tripId", targetNamespace = "")
        int tripId);

}
